// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB32PYCOpFpd6rnAokwyOmLBNsT7ewRXF4',
    appId: '1:79684825941:web:79c754ca07fe03ab3c75dc',
    messagingSenderId: '79684825941',
    projectId: 'sportstalentz',
    authDomain: 'sportstalentz.firebaseapp.com',
    storageBucket: 'sportstalentz.appspot.com',
    measurementId: 'G-MQMB1D08LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxzITXJvrXE_FquQaDdr7ZCwq3aF3ALk',
    appId: '1:79684825941:android:4aa3835e8740c7303c75dc',
    messagingSenderId: '79684825941',
    projectId: 'sportstalentz',
    storageBucket: 'sportstalentz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPQzuZrubP21G7VYsiEGH4EP7zoMR0GjM',
    appId: '1:79684825941:ios:5188ccecb51516f73c75dc',
    messagingSenderId: '79684825941',
    projectId: 'sportstalentz',
    storageBucket: 'sportstalentz.appspot.com',
    iosClientId: '79684825941-b225ag6m205alipjbtqnblf0jlqrrn2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccestalentz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPQzuZrubP21G7VYsiEGH4EP7zoMR0GjM',
    appId: '1:79684825941:ios:5188ccecb51516f73c75dc',
    messagingSenderId: '79684825941',
    projectId: 'sportstalentz',
    storageBucket: 'sportstalentz.appspot.com',
    iosClientId: '79684825941-b225ag6m205alipjbtqnblf0jlqrrn2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.soccestalentz',
  );
}
